apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transaction-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: transaction
  namespaceSelector:
    matchNames:
      - clearledger
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s