server:
  port: 8084

spring:
  application:
    name: clearledger-transaction

  datasource:
    url: jdbc:mysql://mysql:3306/clearledger_system?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true&connectTimeout=10000&socketTimeout=30000
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  expiration: 3600000


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    export:
      prometheus:
        enabled: true
