apiVersion: v1
kind: ConfigMap
metadata:
  CLEARLEDGER_VERSION: "1.0.0"
  CLEARLEDGER_ENV: production
  name: clearledger-config
  namespace: clearledger
data:
  CLEARLEDGER_VERSION: "1.0.0"
  CLEARLEDGER_ENV: production
  SPRING_PROFILES_ACTIVE: prod
  EUREKA_SERVER_URL: http://eureka-server:8761/eureka
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  REDIS_HOST: redis
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clearledger_auth
  SPRING_DATASOURCE_USERNAME: clearledger
  SPRING_DATASOURCE_PASSWORD: clearledger123
  spring.kafka.bootstrap-servers: kafka:9092