apiVersion: v1
kind: Secret
metadata:
  name: clearledger-secret
  namespace: clearledger
type: Opaque
stringData:
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: Abrar@1234
  private.key: |

    

  public.key: |

    

  EMAIL_PASSWORD:
  RAZORPAY_KEY:
  RAZORPAY_SECRET: