apiVersion: apps.kruise.io/v1beta1
kind: CloneSet
metadata:
  name: loan
  namespace: clearledger
spec:
  replicas: 6

  selector:
    matchLabels:
      app: loan

  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
        - name: loan
          image: clearledger/clearledger-loan:v1.0.3
          envFrom:
            - configMapRef:
                name: clearledger-config
            - secretRef:
                name: clearledger-secret
          ports:
            - name: http
            - containerPort: 8086
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

  updateStrategy:
    type: InPlaceIfPossible   # ✅ FIXED HERE

    rollingUpdate:
      partition: 4
      maxUnavailable: 1
      maxSurge: 1

---
apiVersion: v1
kind: Service
metadata:
  name: loan
  namespace: clearledger
spec:
  selector:
    app: loan
  ports:

    - port: 8086
      targetPort: 8086