server:
  port: 8085

spring:
  application:
    name: clearledger-notification


  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


  mail:
    host: smtp.gmail.com
    port: 587
    username: admin@clearledger.io
    password: ${EMAIL_PASSWORD:wtliwgoqkzrgrlcg}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    export:
      prometheus:
        enabled: true


spring:
  mail:
    default-encoding: UTF-8

clearledger:
  notification:
    async-pool-size: 10
